apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: cats-dogs-api-dashboard
    files:
      - dashboards/cats-dogs-api.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
