apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cats-dogs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deepakkt/bits-aiml-mlops-assignment-2.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: cats-dogs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
