apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs-api
spec:
  type: ClusterIP
  selector:
    app: cats-dogs-api
  ports:
    - name: http
      port: 8000
      targetPort: http
