apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: docker.io/local/cats-dogs-classifier
    newName: docker.io/deepakkt/cats-dogs-classifier
    newTag: cac169e5946e0c935f3abc0258db4dd97435cf98

patchesStrategicMerge:
  - patch-env.yaml
