apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: docker.io/local/cats-dogs-classifier
    newName: docker.io/deepakkt/cats-dogs-classifier
    newTag: 33039d1e4ba82810be7c56b4e5d3bd7973d5a6ce

patchesStrategicMerge:
  - patch-env.yaml
