apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: docker.io/local/cats-dogs-classifier
    newName: docker.io/deepakkt/cats-dogs-classifier
    newTag: 4bab8ad54aa04facb7b0294648d0f932d180aee8

patchesStrategicMerge:
  - patch-env.yaml
