apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: docker.io/local/cats-dogs-classifier
    newName: docker.io/deepakkt/cats-dogs-classifier
    newTag: 2d7d869bec037d9b5e58252e638ef9341fa94bae

patchesStrategicMerge:
  - patch-env.yaml
